DEFAULT_TARGETS = {
  :adm_dom  =>  { :direction  => :to   },
  :adm_sch  =>  { :direction  => :to   },
  :adm_ent  =>  { :direction  => :to   },
  :adms     =>  { :direction  => :to   },
  :adm      =>  { :direction  => :to   },
  
  :dc       =>  { :direction  => :to   },
  :rodc     =>  { :direction  => :to   },
  :cdc      =>  { :direction  => :to   },
  :erodc    =>  { :direction  => :to   },
  
  :accop    =>  { :direction  => :to   },
  :srvop    =>  { :direction  => :to   },
  :backop   =>  { :direction  => :to   },
  :printop  =>  { :direction  => :to   },
  :cryptop  =>  { :direction  => :to   },
  :netop    =>  { :direction  => :to   },
  :axxop    =>  { :direction  => :to   },
  
  :dom_usr  =>  { :direction  => :from },
  :dom_cmp  =>  { :direction  => :from },
  :dom_gue  =>  { :direction  => :from },
  :usr      =>  { :direction  => :from },
  :guests   =>  { :direction  => :from },
  :guest    =>  { :direction  => :from },
  :prew2k   =>  { :direction  => :from },
  :waac     =>  { :direction  => :from },
  
  :certpub  =>  { :direction  => :to   },
  :gpoco    =>  { :direction  => :to   },
  :incftb   =>  { :direction  => :to   },
  :krbtgt   =>  { :direction  => :to   },
}

TRANSLATION_TABLE = {
  :en => {
    :adm_dom => "cn=domain admins,",
    :adm_sch => "cn=schema admins,",
    :adm_ent => "cn=enterprise admins,",
    :adms    => "cn=administrators,",
    :adm     => "cn=administrator,",
    
    :dc      => "cn=domain controllers,cn=users,dc=",
    :rodc    => "cn=read-only domain controllers,cn=users,dc=",
    :cdc     => "cn=cloneable domain controllers,cn=users,dc=",
    :erodc   => "cn=enterprise read-only domain controllers,cn=users,dc=",

    :accop   => "cn=account operators,cn=builtin,dc=",
    :srvop   => "cn=server operators,cn=builtin,dc=",
    :backop  => "cn=backup operators,cn=builtin,dc=",
    :printop => "cn=print operators,cn=builtin,dc=",
    :cryptop => "cn=cryptographic operators,cn=builtin,dc=",
    :netop   => "cn=network configuration operators,cn=builtin,dc=",
    :axxop   => "cn=access control assistance operators,cn=builtin,dc=",
    
    :dom_usr => "cn=domain users,cn=users,dc=",
    :dom_cmp => "cn=domain computers,cn=users,dc=",
    :dom_gue => "cn=domain guests,cn=users,dc=",
    :usr     => "cn=users,cn=builtin,dc=",
    :guests  => "cn=guests,cn=builtin,dc=",
    :guest   => "cn=guest,cn=users,dc=",
    :prew2k  => "cn=pre-windows 2000 compatible access,cn=builtin,dc=",
    :waac    => "cn=windows authorization access group,cn=builtin,dc=",
    
    :certpub => "cn=cert publishers,cn=users,dc=",
    :gpoco   => "cn=group policy creator owners,cn=users,dc=",
    :incftb  => "cn=incoming forest trust builders,cn=builtin,dc=",
    :krbtgt  => "cn=krbtgt,cn=users,dc=",
  },
  :fr => {
    :adm_dom => "cn=admins du domaine,",
    :adm_sch => "cn=adminstrateurs du schema,",
    :adm_ent => "cn=administrateurs de l.entreprise,",
    :adms    => "cn=administrateurs,",
    :adm     => "cn=administrator,",
    
    :dc      => "cn=contr.leurs de domaine,cn=users,dc=",
    :rodc    => "cn=contr.leurs de domaine en lecture seule,cn=users,dc=",
    :cdc     => "cn=contr.leurs de domaine clonables,cn=users,dc=",
    :erodc   => "cn=contr.leurs de domaine d.entreprise en lecture seule,cn=users,dc=",

    :accop   => "cn=op.rateurs de compte,cn=builtin,dc=",
    :srvop   => "cn=op.rateurs de serveur,cn=builtin,dc=",
    :backop  => "cn=op.rateurs de sauvegarde,cn=builtin,dc=",
    :printop => "cn=op.rateurs d.impression,cn=builtin,dc=",
    :cryptop => "cn=op.rateurs de chiffrement,cn=builtin,dc=",
    :netop   => "cn=op.rateurs de configuration r.seau,cn=builtin,dc=",
    :axxop   => "cn=op.rateurs d.assistance de contr.le d.acc.s,cn=builtin,dc=",

    :dom_usr => "cn=utilisateurs du domaine,cn=users,dc=",
    :dom_cmp => "cn=ordinateurs du domaine,cn=users,dc=",
    :dom_gue => "cn=invit. du domaine,cn=users,dc=",
    :usr     => "cn=utilisateurs,cn=builtin,dc=",
    :guests  => "cn=invit.s,cn=builtin,dc=",
    :guest   => "cn=invit.,cn=users,dc=",
    :prew2k  => "cn=acc.s compatible pr.-windows 2000,cn=builtin,dc=",
    :waac    => "cn=groupe d.acc.s d.autorisation windows,cn=builtin,dc=",
    
    :certpub => "cn=.diteurs de certificats,cn=users,dc=",
    :gpoco   => "cn=propri.taires cr.ateurs de la strat.gie de groupe,cn=users,dc=",
    :incftb  => "cn=g.n.rateurs d.approbations de for.t entrante,cn=builtin,dc=",
    :krbtgt  => "cn=krbtgt,cn=users,dc=",
  }
}
